name: gene
services:
  backend:
    build:
      context: backend
      args:
        NODE_IMAGE: ${NODE_IMAGE}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend/data:/app/data
    environment:
      - PORT=${BACKEND_PORT}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "${API_URL}/health-check"]
      start_period: 30s
      start_interval: 1s
      interval: 10s
      timeout: 1s
      retries: 3

  frontend:
    build:
      context: frontend
      args:
        NODE_IMAGE: ${NODE_IMAGE}
        VITE_API_URL: ${API_URL}
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
